// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "FirstName1",
                            LastName = "LastName1",
                            UserName = "U1"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "FirstName2",
                            LastName = "LastName2",
                            UserName = "U2"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "FirstName3",
                            LastName = "LastName3",
                            UserName = "U3"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "FirstName4",
                            LastName = "LastName4",
                            UserName = "U4"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "FirstName5",
                            LastName = "LastName5",
                            UserName = "U5"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "FirstName6",
                            LastName = "LastName6",
                            UserName = "U6"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "FirstName7",
                            LastName = "LastName7",
                            UserName = "U7"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "FirstName8",
                            LastName = "LastName8",
                            UserName = "U8"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "FirstName9",
                            LastName = "LastName9",
                            UserName = "U9"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "FirstName10",
                            LastName = "LastName10",
                            UserName = "U10"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "FirstName11",
                            LastName = "LastName11",
                            UserName = "U11"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "FirstName12",
                            LastName = "LastName12",
                            UserName = "U12"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "FirstName13",
                            LastName = "LastName13",
                            UserName = "U13"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "FirstName14",
                            LastName = "LastName14",
                            UserName = "U14"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "FirstName15",
                            LastName = "LastName15",
                            UserName = "U15"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "FirstName16",
                            LastName = "LastName16",
                            UserName = "U16"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "FirstName17",
                            LastName = "LastName17",
                            UserName = "U17"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "FirstName18",
                            LastName = "LastName18",
                            UserName = "U18"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "FirstName19",
                            LastName = "LastName19",
                            UserName = "U19"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "FirstName20",
                            LastName = "LastName20",
                            UserName = "U20"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "FirstName21",
                            LastName = "LastName21",
                            UserName = "U21"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "FirstName22",
                            LastName = "LastName22",
                            UserName = "U22"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "FirstName23",
                            LastName = "LastName23",
                            UserName = "U23"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "FirstName24",
                            LastName = "LastName24",
                            UserName = "U24"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "FirstName25",
                            LastName = "LastName25",
                            UserName = "U25"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "FirstName26",
                            LastName = "LastName26",
                            UserName = "U26"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "FirstName27",
                            LastName = "LastName27",
                            UserName = "U27"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "FirstName28",
                            LastName = "LastName28",
                            UserName = "U28"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "FirstName29",
                            LastName = "LastName29",
                            UserName = "U29"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "FirstName30",
                            LastName = "LastName30",
                            UserName = "U30"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "FirstName31",
                            LastName = "LastName31",
                            UserName = "U31"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "FirstName32",
                            LastName = "LastName32",
                            UserName = "U32"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "FirstName33",
                            LastName = "LastName33",
                            UserName = "U33"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "FirstName34",
                            LastName = "LastName34",
                            UserName = "U34"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "FirstName35",
                            LastName = "LastName35",
                            UserName = "U35"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "FirstName36",
                            LastName = "LastName36",
                            UserName = "U36"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "FirstName37",
                            LastName = "LastName37",
                            UserName = "U37"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "FirstName38",
                            LastName = "LastName38",
                            UserName = "U38"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "FirstName39",
                            LastName = "LastName39",
                            UserName = "U39"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "FirstName40",
                            LastName = "LastName40",
                            UserName = "U40"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "FirstName41",
                            LastName = "LastName41",
                            UserName = "U41"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "FirstName42",
                            LastName = "LastName42",
                            UserName = "U42"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "FirstName43",
                            LastName = "LastName43",
                            UserName = "U43"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "FirstName44",
                            LastName = "LastName44",
                            UserName = "U44"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "FirstName45",
                            LastName = "LastName45",
                            UserName = "U45"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "FirstName46",
                            LastName = "LastName46",
                            UserName = "U46"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "FirstName47",
                            LastName = "LastName47",
                            UserName = "U47"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "FirstName48",
                            LastName = "LastName48",
                            UserName = "U48"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "FirstName49",
                            LastName = "LastName49",
                            UserName = "U49"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "FirstName50",
                            LastName = "LastName50",
                            UserName = "U50"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "FirstName51",
                            LastName = "LastName51",
                            UserName = "U51"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "FirstName52",
                            LastName = "LastName52",
                            UserName = "U52"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "FirstName53",
                            LastName = "LastName53",
                            UserName = "U53"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "FirstName54",
                            LastName = "LastName54",
                            UserName = "U54"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "FirstName55",
                            LastName = "LastName55",
                            UserName = "U55"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "FirstName56",
                            LastName = "LastName56",
                            UserName = "U56"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "FirstName57",
                            LastName = "LastName57",
                            UserName = "U57"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "FirstName58",
                            LastName = "LastName58",
                            UserName = "U58"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "FirstName59",
                            LastName = "LastName59",
                            UserName = "U59"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "FirstName60",
                            LastName = "LastName60",
                            UserName = "U60"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "FirstName61",
                            LastName = "LastName61",
                            UserName = "U61"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "FirstName62",
                            LastName = "LastName62",
                            UserName = "U62"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "FirstName63",
                            LastName = "LastName63",
                            UserName = "U63"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "FirstName64",
                            LastName = "LastName64",
                            UserName = "U64"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "FirstName65",
                            LastName = "LastName65",
                            UserName = "U65"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "FirstName66",
                            LastName = "LastName66",
                            UserName = "U66"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "FirstName67",
                            LastName = "LastName67",
                            UserName = "U67"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "FirstName68",
                            LastName = "LastName68",
                            UserName = "U68"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "FirstName69",
                            LastName = "LastName69",
                            UserName = "U69"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "FirstName70",
                            LastName = "LastName70",
                            UserName = "U70"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "FirstName71",
                            LastName = "LastName71",
                            UserName = "U71"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "FirstName72",
                            LastName = "LastName72",
                            UserName = "U72"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "FirstName73",
                            LastName = "LastName73",
                            UserName = "U73"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "FirstName74",
                            LastName = "LastName74",
                            UserName = "U74"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "FirstName75",
                            LastName = "LastName75",
                            UserName = "U75"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "FirstName76",
                            LastName = "LastName76",
                            UserName = "U76"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "FirstName77",
                            LastName = "LastName77",
                            UserName = "U77"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "FirstName78",
                            LastName = "LastName78",
                            UserName = "U78"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "FirstName79",
                            LastName = "LastName79",
                            UserName = "U79"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "FirstName80",
                            LastName = "LastName80",
                            UserName = "U80"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "FirstName81",
                            LastName = "LastName81",
                            UserName = "U81"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "FirstName82",
                            LastName = "LastName82",
                            UserName = "U82"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "FirstName83",
                            LastName = "LastName83",
                            UserName = "U83"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "FirstName84",
                            LastName = "LastName84",
                            UserName = "U84"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "FirstName85",
                            LastName = "LastName85",
                            UserName = "U85"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "FirstName86",
                            LastName = "LastName86",
                            UserName = "U86"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "FirstName87",
                            LastName = "LastName87",
                            UserName = "U87"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "FirstName88",
                            LastName = "LastName88",
                            UserName = "U88"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "FirstName89",
                            LastName = "LastName89",
                            UserName = "U89"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "FirstName90",
                            LastName = "LastName90",
                            UserName = "U90"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "FirstName91",
                            LastName = "LastName91",
                            UserName = "U91"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "FirstName92",
                            LastName = "LastName92",
                            UserName = "U92"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "FirstName93",
                            LastName = "LastName93",
                            UserName = "U93"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "FirstName94",
                            LastName = "LastName94",
                            UserName = "U94"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "FirstName95",
                            LastName = "LastName95",
                            UserName = "U95"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "FirstName96",
                            LastName = "LastName96",
                            UserName = "U96"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "FirstName97",
                            LastName = "LastName97",
                            UserName = "U97"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "FirstName98",
                            LastName = "LastName98",
                            UserName = "U98"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "FirstName99",
                            LastName = "LastName99",
                            UserName = "U99"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "FirstName100",
                            LastName = "LastName100",
                            UserName = "U100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
